In [1]:
import numpy as np

In [3]:
# Q 1 = Create an array of integers between -10 and 10
a=np.arange(-10 ,10)
print(a)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]


In [6]:
# Q 2 = Run the following code to create a NumPy array D
#D = np.array(range(18)) + 3

# (a) = Extract every other value from array D starting from the 2nd value through the 10th value. Store the result in a variable called x.

D = np.array(range(18)) + 3
print(D)


[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [8]:
x=D[2:10]
print(x)

[ 5  6  7  8  9 10 11 12]


In [10]:
# (b) =  Extract every other value from array D starting from the 10th value through the 2nd value. Store the result in a variable called y.
x=D[2:10]
y=x[::-1]
print(y)

[12 11 10  9  8  7  6  5]


In [11]:
# (c) = Create a variable z that contains all of the values in D in reverse order.
z=D[::-1]
z

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3])

In [ ]:
# Q3 = How are NumPy Arrays better than Lists in Python? 
#answer = consumes less memory.
#        fast as compared to the python List.
#        convenient to use.

-------------------------------------------------------------------------------------------------------------------------------------------
#Q4 = Explain the data types supported by Numpy.
#answer = bool = It represents the boolean value indicating true or false. It is stored as a byte.
#         int  = It is the default type of integer. It is identical to long type in C that contains 64 bit or 32-bit integer.
#         intc = It is similar to the C integer (c int) as it represents 32 or 64-bit int.
#         intp = It represents the integers which are used for indexing.
#         int8 = It is the 8-bit integer identical to a byte. The range of the value is -128 to 127.
#         int16= It is the 2-byte (16-bit) integer. The range is -32768 to 32767.
#         int32 =It is the 4-byte (32-bit) integer. The range is -2147483648 to 2147483647.
#         int64 =It is the 8-byte (64-bit) integer. The range is -9223372036854775808 to 9223372036854775807.
#         uint8 = It is the 1-byte (8-bit) unsigned integer.
#         uint16 = It is the 2-byte (16-bit) unsigned integer.
#         uint32 = It is the 4-byte (32-bit) unsigned integer.
#         uint64 = It is the 8 bytes (64-bit) unsigned integer.
#         float = It is identical to float64.
#         float16 = It is the half-precision float. 5 bits are reserved for the exponent. 10 bits are reserved for mantissa, and 1 bit is reserved for the sign.
#         float32 = It is a single precision float. 8 bits are reserved for the exponent, 23 bits are reserved for mantissa, and 1 bit is reserved for the sign.
#         float64 = It is the double precision float. 11 bits are reserved for the exponent, 52 bits are reserved for mantissa, 1 bit is used for the sign.
#         complex = It is identical to complex128.
#         complex64 = It is used to represent the complex number where real and imaginary part shares 32 bits each.
#         complex128 = It is used to represent the complex number where real and imaginary part shares 64 bits each